- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/discovery.py
- bleak/backends/dotnet/client.py
I've been trying out the develop branch and ran into a few issues with BlueZ. See commit messages for details. I can split these into individual pull requests if that is helpful.
> BlueZ fixes for develop branch

- bleak/backends/bluezdbus/discovery.py
If the rules are only added to Bluez via DBus but never removed again,
the calls pile up if discover() is called multiple times in one session.
This is especially harmful for long-running applications that connect
and disconnect to the same or different servers over and over. The time
to await discovery() becomes very long (up to minutes) even with smaller
timeouts.
Make sure the callbacks registered are cleaned up before discover() is
left.
Fixes #89
> Fix leaking of callbacks from DBus on multiple calls to discover()

- bleak/backends/dotnet/discovery.py
Enable active scanning during discovery and check scan responses for local name.
For my custom BLE device, this fixes https://github.com/hbldh/bleak/issues/95
> .Net: Fix local names when they're in the scan response packet

- Pipfile
- bleak/backends/bluezdbus/client.py
Upstream bug fix has finally been merged and released, so we can
bump the version and remove the comment about the bug.
> Update to txdbus v1.1.1

- bleak/backends/dotnet/client.py
Since we're an async library, we probably don't want to run the
callbacks from a different thread than the one the event loop is running
from.
> backends/dotnet: run callbacks from main thread

- bleak/backends/corebluetooth/CentralManagerDelegate.py
Detailed descibed in Issue #185
> Fixed is_disconnected issue in CoreBluetooth client, Issue #185

- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/client.py
I made the changes on top on feature/find-device-850aba9 yesterday, so that's why they are here.
> RSSI feature, Notifiy by handle fix, event.wait() fix

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/device.py
- bleak/backends/dotnet/client.py
- bleak/backends/dotnet/utils.py
- docs/backends/macos.rst
Might fix #64
Might fix #77
Might fix #203 
Fixes #218
> First drafts of "Just Works" pairing for .NET and BlueZ backends

- CHANGELOG.rst
- bleak/backends/dotnet/client.py
- bleak/backends/dotnet/discovery.py
- bleak/backends/dotnet/scanner.py
This fixes some issues with the Windows disconnect callback implementation (e.g. #312 and #313). 
It also contains further improvements for managing the connection lifecycle.
> Windows connection fixes

- AUTHORS.rst
- CHANGELOG.rst
- bleak/backends/corebluetooth/scanner.py
3. The pull request should work for Python 3.6+ on the following platforms:
5. Feel free to add your name as a contributor to the `AUTHORS.rst` file!
> adv_service_data

- CHANGELOG.rst
- bleak/backends/dotnet/client.py
I guess I prefer behaviour change, but for now I aligned the docstring better with the current behaviour.
> updating docstring for dotnet.client.BleakClientDotNEt connect method

- bleak/backends/bluezdbus/scanner.py
This was leftover from when we were using txdbus.
> Remove dead code in BlueZ backend

- .github/workflows/build_and_test.yml
- CHANGELOG.rst
- Pipfile
- bleak/__init__.py
- bleak/__version__.py
- bleak/backends/bluezdbus/service.py
- bleak/backends/dotnet/client.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/dotnet/service.py
- bleak/backends/service.py
- bleak/backends/winrt/characteristic.py
- bleak/backends/winrt/client.py
- bleak/backends/winrt/descriptor.py
- bleak/backends/winrt/scanner.py
- bleak/backends/winrt/service.py
- requirements.txt
- setup.py
- tests/test_imports.py
> Brought the WinRT backend up to date with develop

- examples/uart_service.py
This fixes up the uart example a bit. See commit messages for details.
> Uart example improvements

- CHANGELOG.rst
- bleak/backends/bluezdbus/scanner.py
3. The pull request should work for Python 3.7+ on the following platforms:
5. Feel free to add your name as a contributor to the `AUTHORS.rst` file!
> small bug fix to set the metadata on the device on discovery callback

- examples/detection_callback.py
Adding 100s of UUIDs to the scan filter on BlueZ causes BlueZ to fail
with:
File "examples/detection_callback.py", line 53, in <module>
asyncio.run(main(service_uuids))
File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "examples/detection_callback.py", line 42, in main
await scanner.start()
File "/home/david/work/pybricks/bleak/bleak/backends/bluezdbus/scanner.py", line 169, in start
assert_reply(reply)
File "/home/david/work/pybricks/bleak/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: …
> Limit "all" option to Mac.

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
> bluezdbus: Return the battery percentage in an array

- bleak/backends/bluezdbus/utils.py
Simple fix in documentation of method describing the errors that could be raised.
> Fix documentation of raised error

- bleak/backends/bluezdbus/advertisement_monitor.py
Just cosmetic, underline the title completely with '-' dashes.
> Underline title completely

- bleak/backends/bluezdbus/advertisement_monitor.py
- bleak/backends/bluezdbus/manager.py
This replaces the callback mechanism in BlueZ passive scanning with the one from active scanning. This makes both scans work the same.
After some experimentation, we realized that the BlueZ advertisement monitor APIs are really just for detecting if a device goes in range or out of range, which isn't what we need in Bleak. So basically, we are just using it as a hack to initiate passive scanning since there isn't a flag in "StartDiscovery" or "SetDiscoveryFilter" to select passive scanning.
> bluez: use same callback for passive and active scan

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/version.py
- tests/bleak/backends/bluezdbus/test_version.py
see commit messages for details
> BlueZ battery fixes

- CONTRIBUTING.rst
- README.rst
- docs/installation.rst
- docs/scanning.rst
- docs/usage.rst
This updates the docs for recent changes in dependency management.
> docs: update for recent changes

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/service.py
- bleak/backends/characteristic.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/characteristic.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/descriptor.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/corebluetooth/service.py
- bleak/backends/p4android/characteristic.py
- bleak/backends/p4android/client.py
- bleak/backends/p4android/descriptor.py
- bleak/backends/p4android/scanner.py
- bleak/backends/p4android/service.py
- bleak/backends/p4android/utils.py
- bleak/backends/scanner.py
- bleak/backends/service.py
- bleak/backends/winrt/characteristic.py
- bleak/backends/winrt/client.py
- bleak/backends/winrt/descriptor.py
- bleak/backends/winrt/service.py
This changes all remaining library files to use relative imports. Some files are already doing this since we have circular imports in a few places. This also sorts other imports while we are touching this.
> use relative imports

- bleak/__init__.py
> bleak: fix backend kwarg type hint

- bleak/backends/bluezdbus/manager.py
This fixes a mypy error about incompatible types.
> backends/bluezdbus/manager: fix weak map type

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/utils.py
- poetry.lock
- pyproject.toml
A faster `unpack_variants` is now provided by dbus-fast
> Use unpack_variants from dbus-fast

- bleak/backends/winrt/client.py
The fix from #1101 causes the following when run with `python3.10 -X dev`.
ERROR:asyncio:Exception in callback Future.set_result(<Future cance...events.py:429>, <_bleak_winrt...001C33C60B100>)
handle: <Handle Future.set_result(<Future cance...events.py:429>, <_bleak_winrt...001C33C60B100>)>
File "C:\Users\david\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
ERROR:asyncio:Exception in callback Future.set_result(<Future cance...events.py:429>, <_bleak_winrt...001C33C60BFC0>)
handle: <Handle Future.set_result(<Future cance...events.py:429>, <_bleak_winrt...001C33C60BFC0>)>
File …
> winrt/client: add FutureLike wrapper for IAsyncOperation

- CHANGELOG.rst
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/p4android/scanner.py
- bleak/backends/scanner.py
- bleak/backends/winrt/scanner.py
This PR adds some type hints for the return type of some scanner methods, as they were reported by mypy in strict mode for my application using Bleak.
> Add return type None to some scanner methods

- .github/workflows/build_and_test.yml
This fixes macos builds with older versions of Python.
> github: set SYSTEM_VERSION_COMPAT=0

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/scanner.py
> fix BLEDevice name somtimes incorrectly None

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
https://github.com/hbldh/bleak/issues/1330
> Fix windows scanner crash

- AUTHORS.rst
- CHANGELOG.rst
- poetry.lock
- pyproject.toml
> Update PyObjC dependency on macOS to v10.x

- bleak/__init__.py
> Fix missing f-string in exception message

- CHANGELOG.rst
- bleak/backends/corebluetooth/scanner.py
3. The pull request should work for Python 3.8+ on the following platforms:
5. Feel free to add your name as a contributor to the `AUTHORS.rst` file!
> Ignore None type device address when using bdaddr

- bleak/backends/bluezdbus/utils.py
https://github.com/hbldh/bleak/pull/1517#discussion_r1498306568
> Remove unused validate_address()

- .github/workflows/format_and_lint.yml
- CONTRIBUTING.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/advertisement_monitor.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/utils.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/utils.py
- bleak/backends/p4android/defs.py
- bleak/backends/p4android/recipes/bleak/__init__.py
- bleak/backends/service.py
- bleak/uuids.py
- examples/async_callback_with_queue.py
- examples/disconnect_callback.py
- examples/kivy/main.py
- examples/mtu_size.py
- examples/philips_hue.py
- examples/two_devices.py
- poetry.lock
- pyproject.toml
- tests/bleak/backends/bluezdbus/test_utils.py
- typings/CoreBluetooth/__init__.pyi
- Add isort to pyproject.toml
- Format code using isort
- Add isort to CI lint checks
> sort imports with isort

- bleak/backends/scanner.py
Fixes: https://github.com/hbldh/bleak/issues/1554
> backends/scanner: clarify Tx Power Level

- docs/troubleshooting.rst
It is quite common for people to report "bugs" in Bleak because they are using it wrong. Now we can have a link to give them to explain this in detail.
> docs/troubleshooting: section on asynio.run()

- bleak/uuids.py
additional doc fix for UUIDs
Sorry, my bad, I oversaw 3 more occurrences :disappointed:
> Fix UUID doc

- CHANGELOG.rst
- bleak/backends/winrt/client.py
- docs/conf.py
Some small fixes and improvements made while working on a new feature.
> Misc fixes

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/client.py
- docs/api/client.rst
- examples/service_explorer.py
This is an alternative to #1713 and fixes #309.
> add pair param to BleakClient()

- CHANGELOG.rst
- bleak/exc.py
Small change to correct the description of error 15. Found while testing a BLE device in development.
> Att error 15 name fix

- .github/pull_request_template.md
- CHANGELOG.rst
- CONTRIBUTING.rst
- README.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/bluezdbus/version.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/device.py
- bleak/backends/p4android/client.py
- bleak/backends/scanner.py
- bleak/backends/winrt/client.py
- docs/api/client.rst
- docs/api/index.rst
- docs/api/scanner.rst
- docs/backends/index.rst
- docs/backends/linux.rst
- docs/index.rst
- tests/bleak/backends/bluezdbus/test_version.py
We have quite a few things that have been deprecated with proper warnings now for 3+ years. So let's go ahead and remove those.
> Remove deprecated stuff

- .github/workflows/build_and_test.yml
This is no need to build and run tests if no code changes.
> github: only build and test if code changes

- docs/troubleshooting.rst
Fixes: https://github.com/hbldh/bleak/issues/1747
> docs: update RPi troubleshooting section

- bleak/__init__.py
minor fix for documentation misaligned with code on `BleakCharacteristicNotFoundError`
> fix exception documentation
