hbldh/bleak

- bleak/backends/bluezdbus/client.py
There seems to be no guarantee that services are listed before
characteristics in bluez dbus API. This caused (sometimes) a IndexError
in get_services() as adding a characteristic to a service that did not
exist yet failed.
Not sure if it's the same with descriptors, could possible be in the same 
loop as characteristics?
> Fix IndexError in bluez client

- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
This patch contains two changes:
* Add API and Bluez implementation to set a callback fired when a device disconnects without active intervention from the client
* Remove all existing subscriptions to characteristic notifications when a device disconnects
Replaces #85 
Fixes #83 
Closes #82
> Register a disconnected callback and clean up subscriptions on disconnect

- bleak/backends/bluezdbus/discovery.py
During a call to discover() on the Bluez backend, a DBus connection is
opened, but never closed. If discover() is called multiple times while
the application is running, DBus at some point prevents opening
additional connections.
Make sure the bus connection is closed after discovery.
Fixes #91
> Prevent leaking of DBus connections on discovery

- bleak/backends/bluezdbus/utils.py
Should fix this Python 3 related warning:
```
src/bleak/bleak/backends/bluezdbus/utils.py:10: DeprecationWarning: invalid escape sequence \d
_hci_device_regex = re.compile("^hci(\d+)$")
```
> Use raw literals for regex patterns

- bleak/backends/bluezdbus/client.py
Raise an exception in the infinite loop of `get_services` if the field `Connected` is not found in the properties.
Sometimes we can get stuck in this loop if the connection drops between the connect and the service discovery.
Either we should raise an exception there or return and raise it in the caller.
> Avoid infinite loop by raising an exception if not connected

- bleak/backends/bluezdbus/discovery.py
Allow the user to add any BlueZ filter for the discovery.
> backend(BlueZ): add a discovery filter argument

- bleak/backends/bluezdbus/client.py
This version check gets questioned somewhat frequently. Each time,
it is found to be correct. So, let's add a comment with a detailed
explanation about what is going on.
> bluez: add comment about version check

- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/discovery.py
This contains some fixes for the corebluetooth backend so that the format of the `BLEDevice.metatadata` values are the same on all platforms.
See commit messages for details.
> Fix macOS BLEDevice.metatadata values

- bleak/backends/corebluetooth/PeripheralDelegate.py
Fixes the following error:
```
2020-01-03 00:33:47.366 Python[3151:275686] PyObjC: Converting exception to Objective-C:
File "bleak/backends/corebluetooth/PeripheralDelegate.py", line 250, in peripheral_didUpdateValueForCharacteristic_error_
cUUID in self._characteristic_notify_status
TypeError: argument of type 'bool' is not iterable
2020-01-03 00:33:47.374 Python[3151:275686] *** Terminating app due to uncaught exception 'OC_PythonException', reason: '<class 'TypeError'>: argument of type 'bool' is not iterable'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff2cb4db79 __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff572c13c6 objc_exception_throw + 48
2   CoreFoundation …
```
> Macos type error

- bleak/backends/bluezdbus/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/discovery.py
This makes things much cleaner :
- The default asyncio event loop is not modified
- No default twisted reactor is installed (a new one will be created every time)
- The reactor will use the provided event loop
Related to: #93 #125
> backends/bluezdbus: use an a new reactor for each client

- bleak/backends/corebluetooth/PeripheralDelegate.py
f2aa8d9 fails to account for an edge case the issues found in #114, which results in the while loop in `writeCharacteristic_value_type` never resolving because the peripheral never calls the `didWriteValueForCharacteristic` method.
> On the other hand, if you specify the write type as CBCharacteristicWriteWithoutResponse, Core Bluetooth attempts to write the value but doesn’t guarantee success. If the write doesn’t succeed in this case, you aren’t notified and you don’t receive an error indicating the cause of the failure.
[Apple docs for writeCharacteristic_value_type](https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518747-writevalue?language=objc#discussion)
> **Core Bluetooth invokes this method only when your app calls the writeValue:forCharacteristic:type: …
> macOS: Adapt characteristic write log to account for WriteWithoutResponse.

- bleak/backends/bluezdbus/discovery.py
- bleak/backends/bluezdbus/signals.py
The management of the discovery and clients on Linux is primarly done
through subscribing and listening to DBus messages. The subscriptions
have been identified only through the Interface names and their members.
However, those interfaces are generic and can be implemented by all kind
of applications that expose their API through DBus. This led to the
situation where for example NetworkManager events are forwarded to the
bleak application and handled in the callback.
Although those messages have been ignored, they shouldn't even reach the
application. This patch limits the subscriptions to messages with the
"/org/bluez" path prefix and therefore to relevant BlueZ messages.
Fixes #151
> bluez: only subscribe to BlueZ messages on DBus

- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/device.py
- bleak/backends/corebluetooth/discovery.py
Fixes the following issues on MacOS/CoreBluetooth backend:
- #142. advertisementData such as service UUIDs lost as multiple calls to
centralManager_didDiscoverPeripheral_advertisementData_RSSI_
for same device (but different advertisementData) was not handled.
- Devices never removed only added while scanning and long running
applications would have get incorrect scan result.
- Scan was never stoped if timeout was 0 or None.
> Advertisement data

- bleak/backends/corebluetooth/PeripheralDelegate.py
Removed `_characteristic_notify_status: {bool}` to fix #155.
The following sometimes happened on MacOS:
`peripheral_didUpdateValueForCharacteristic` runs during `asyncio.sleep` below but user `callback` not called as `_characteristic_notify_status[cUUID]`  not True yet. This resulted in that the first notification data received was lost.
```python
async def startNotify_cb_(
self, characteristic: CBCharacteristic, callback: Callable[[str, Any], Any]
) -> bool:
self._characteristic_notify_log[cUUID] = False
self._characteristic_notify_callbacks[cUUID] = callback
self.peripheral.setNotifyValue_forCharacteristic_(True, characteristic)
while not self._characteristic_notify_log[cUUID]:
await asyncio.sleep(0.01)
self._characteristic_notify_status[cUUID] = True
def …
```
> corebluetooth notifications fix

- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
Added disconnected callback variable in `CentralManagerDelegate` class, which being set by the `set_disconencted_callback` function.
CentralManagerDelegate calls the callback function without argument, so I added wrapper function `disconnected_callback_client` in `client` that pads the `client` as argument and calls actual disconnection callback. 
Issue #184
> Added disconnected callback feature for CoreBluetooth

- Pipfile
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/__init__.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/discovery.py
- bleak/backends/corebluetooth/scanner.py
- requirements.txt
- setup.py
This is some of the fixes I have been working on. If fixes several of the outstanding CoreBluetooth issues. I didn't rebase on #209 because that PR seems a bit unfinished.
> CoreBluetooth fixes

- bleak/backends/corebluetooth/PeripheralDelegate.py
This fixes problems running with my code, but there could potentially be other places that is experiencing a similar situation.
> Fix when characteristic updates value faster than asyncio schedule.

- MANIFEST.in
running: 
python setup.py sdist
pip install -t foo dist/bleak-0.7.0.tar.gz
will fail because CHANGELOG.rst is required.  This also breaks source installs from pypi, for example:
pip install bleak --no-binary :all:
included is a trivial fixup
> add CHANGELOG.rst to MANIFEST.in to be able to build sdist

- README.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/discovery.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/bluezdbus/signals.py
- bleak/backends/bluezdbus/utils.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/discovery.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/dotnet/client.py
- bleak/backends/dotnet/discovery.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/dotnet/utils.py
- bleak/backends/scanner.py
- docs/usage.rst
- examples/disconnect_callback.py
- examples/enable_notifications.py
- examples/get_services.py
- examples/sensortag.py
- examples/service_explorer.py
This removes most cases of passing the asyncio event loop as an argument (some cases are kept in the Linux backend for interop with txdbus/twisted).
Passing the loop as an argument has been deprecated in Python 3.8 and will be removed in 3.10.
Explanation: https://stackoverflow.com/a/60315290/1976323
This is a breaking change, but it seems better to do it now rather than wait for it to break in Python itself in a few years.
> Remove passing of asyncio event loop as argument.

- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
It seems that these expect all delegate members to be implemented, however in reality only the `CentralManagerDelegate` `didUpdateState` callback is required. All other methods are optional, so this warning is not particularly useful.
> remove objc delegate compliance checks

- bleak/backends/bluezdbus/client.py
Support for the "type" option was actually added in v5.51, not v5.50.
See https://github.com/hbldh/bleak/pull/260#issuecomment-666717033
> Fix BlueZ version typo.

- bleak/backends/corebluetooth/client.py
The get_services function incorrectly returns the underlying `_service` array rather than the services object when reading it from the cache.
> Fix get_services function of corebluetooth client

- CHANGELOG.rst
- bleak/__version__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/bluezdbus/utils.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/discovery.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/dotnet/client.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/scanner.py
- bleak/utils.py
- docs/backends/macos.rst
- docs/scanning.rst
- examples/scanner.py
A new method in the `BleakScanner` interface. Using the scanner soution, one can remove the hard wait time in `connect` calls with a much faster, variable time scanning which exits when the sought device has been detected by the scanner. This will result in generally faster connections and hopefully more stable connects as well.
> Implementation of `find_specific_device` feature

- CHANGELOG.rst
- bleak/__version__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/dotnet/client.py
**POTENTIAL BREAKING CHANGE**: All notifications now have the characteristic's integer **handle** instead of its UUID as a string as the first argument ``sender`` sent to notification callbacks. This provides the uniqueness of sender in notifications as well.
This dawned on me when reviewing and merging #273. I think it is more correct this way, but it might break some existing code.
> Change uuid to handle in data sent to notification callbacks

- bleak/__init__.py
The previous check does not working on macOS Big Sur as it presumes that Core Bluetooth was already loaded on the process.
Superseeds #278
> Safer `Core Bluetooth` presence check

- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/device.py
On MacOS you may get two callbacks when running a discovery: one when the `ADV_IND` packet arrives and a second one (in case of an active scan) when the SCAN_RSP packet arrives.
Bleak always picks up the device name only from the first packet (if it is in there). Bleak also overwrites any service UUIDs from the first packet if there are service UUIDs in the second packet.
This PR fixes both issues. It also addresses my main reason for #281
> Handle 2-stage discovery on MacOS better

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/dotnet/client.py
- examples/connect_by_bledevice.py
* Added the possibility to connect using ``BLEDevice`` instead of a string adress. This allows for skipping the discovery call when connecting.
* Renamed ``BleakClient`` argument ``address`` to ``address_or_device``. 
Fixes #191 
Improves #284
> Connect by BLEDevice as well as string Bluetooth adress

- bleak/backends/dotnet/client.py
The logic was inverted. If a device was given in the BleakClient constructor, then the _device_info attribute is set to the Bluetooth address, otherwise it is set to None. So we should only trying scanning for the device if _device_info is None.
> Fix device_info logic in dotnet client

- bleak/backends/bluezdbus/characteristic.py
- bleak/backends/bluezdbus/client.py
The "Handle" property of the org.bluez.GattCharacteristic1 D-Bus interface is server-only, so it isn't available to Bleak. Instead,
we can scrape the handle from the D-Bus path of the characteristic.
Full object path format for reference:
[variable prefix]/{hci0,hci1,...}/dev_XX_XX_XX_XX_XX_XX/serviceXX/charYYYY
Fixes #292
> Fix getting handle in BlueZ backend

- bleak/backends/corebluetooth/client.py
In 666395e26b8a, `_disconnected_callback_client()` was accidentally deleted instead of `set_disconnected_callback()`. This restores the former and deletes the latter.
Fixes #294
> Fix deleting wrong method in CoreBluetooth backend

- bleak/backends/bluezdbus/client.py
I have seen cases where this would get hung up.  It seems like it can be fixed by simply passing the same argument into the DBus request.  In theory the timeout could be 2x the `timeout` value.  If we care about that, we could do `timeout/2` but the intent is moreso that it does not hang forever.
> Adding timeout to dbus call as well to make sure it doesn't hang forever

- bleak/backends/bluezdbus/characteristic.py
Seems like some old code was hanging around.  Updating to simply use the `uuid` property.  Should be a straightforward fix.
> `_uuid` is not defined.  Updating to point to `uuid` property.

- bleak/backends/bluezdbus/client.py
This will cause errors when passing a `BleDevice` instance as argument. Base class already handles this and sets the address according to the type of `address_or_ble_device`.
> Prevent overwriting address in dbus client

- bleak/backends/bluezdbus/client.py
> Catch RemoteError in is_connected in BlueZ backend (#310)

- .github/workflows/build_and_test.yml
- .github/workflows/format_and_lint.yml
- bleak/backends/bluezdbus/client.py
--diff does not cause a test to fail, so it is easy to miss
> github: use --check instead of --diff for black

- CHANGELOG.rst
- bleak/backends/bluezdbus/characteristic.py
- bleak/backends/bluezdbus/descriptor.py
- bleak/backends/bluezdbus/service.py
- bleak/backends/characteristic.py
- bleak/backends/corebluetooth/characteristic.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/descriptor.py
- bleak/backends/corebluetooth/service.py
- bleak/backends/corebluetooth/utils.py
- bleak/backends/descriptor.py
- bleak/backends/dotnet/characteristic.py
- bleak/backends/dotnet/service.py
- bleak/backends/service.py
I recently ran into an issue where calling methods such as` BleakGattService.get_characteristic()` with a string for the UUID that contained uppercase letters would fail even though the UUID was otherwise correct.
This fixes that issue and includes some more cleanups in related code.
> UUID fixes and cleanups

- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
If `disconnect()` is called more than once it will try to operate a _None_ object, which can cause some low-level assertion errors in CoreBluetooth and leave Bleak in a strange state.
This is related to #319
> Avoiding 'None' case when disconnecting

- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
I have seen connect get itself in a state where will loop indefinitely.  This timeout fix seems to fix it.  `time.time()` seems like a hack, but I cannot think of a better way offhand.  Open to suggestions.
> Adding a timeout on OSX so that the connect cannot hang forever.

- CHANGELOG.rst
- bleak/backends/corebluetooth/device.py
- bleak/backends/corebluetooth/scanner.py
This was missed in 6a0d8c99f5c82b6b1c000316fb1c0dff49a92138.
Also, since this was just using `str()` directly on the `CBUUID` instance, it had an additional bug for well known services since `str()` would return the name of the service instead of a UUID.
Fixes #342.
> corebluetooth: use cb_uuid_to_str() to convert kCBAdvDataServiceUUIDs

- CHANGELOG.rst
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/device.py
- bleak/backends/corebluetooth/discovery.py
- bleak/backends/corebluetooth/scanner.py
First commit fixes possible race condition when using `CBCentralManager` in rare cases. (I was also getting a `asyncio.TimeoutError` from `wait_for_powered_on()` when running using a debugger that is fixed by this.)
Second commit fixes a regression from 583c08e4bf1b.
> macOS fixes

- CHANGELOG.rst
- Pipfile
- requirements.txt
This avoids a crash on macOS <= 10.15 in PyObjC 7.0.0.
Fixes #372
> CoreBluetooth: update PyObjC to 7.0.1

- CHANGELOG.rst
- bleak/backends/dotnet/discovery.py
- bleak/backends/dotnet/scanner.py
Windows .NET event handler callbacks run on a background thread, so we need to use `call_soon_threadsafe()` to schedule the callbacks in the asyncio event loop. See commit messages for more details.
> fix dotnet event callbacks

- CHANGELOG.rst
- bleak/backends/corebluetooth/scanner.py
> Fixed ``BleakScanner.discover()`` on older versions of macOS.

- AUTHORS.rst
- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/discovery.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/dotnet/discovery.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/scanner.py
- docs/scanning.rst
- examples/detection_callback.py
Implementation for standardizing callback arguments passed to callback functions to make use easier across platforms (resolves #301).
This implements the feature for all platforms and include doc updates and an example.
> Standardizing arguments passed to callback functions

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
`add_done_callback()` calls the callback with one argument. This was causing `self._disconnected_callback()` to be called with two arguments but as in the disconnect example, it only expects one argument.
By replacing the partial function with a lambda expression, we can just ignore the extra argument.
> Fixed disconnect callback on BlueZ backend.

- CHANGELOG.rst
- bleak/backends/corebluetooth/client.py
If `BleakClient.is_connected()` is called before `BleakClient.connect()`, `self._central_manager_delegate` will be `None`, which was leading to a crash.
Fixes #385
> Fixed calling BleakClient.is_connected() on Mac before connection.

- bleak/backends/bluezdbus/utils.py
The changelog says this was removed in v0.7.0, but it is still here.
> Removed dead code in BlueZ backend.

- CHANGELOG.rst
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/scanner.py
Since #334, all backends have the same implementation of `BleakScanner.register_detection_callback()` and the documentation was out of date.
This consolidates the implementation in the abstract base class and updates the type hints and documentation.
> Consolidated implementation of BleakScanner.register_detection_callback()

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/device.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/device.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/scanner.py
- docs/scanning.rst
- examples/detection_callback.py
After using the changes from #334 a bit more, I found myself wanting a `BLEDevice` in addition to the `AdvertismentData`. This way if out find a device you like, you can pass the `BLEDevice` to `BleakClient()` directly without having to find it again in the list returned by `get_discovered_devices()`.
Technically, some things like the device identifier (address or UUID on Mac) and RSSI aren't part of the advertising data and were already in `BLEDevice` so I removed them from `AdvertisingData`. This also opened the opportunity to clean up some other things along the way.
@Bernstern, does this work for you?
> Detection callback improvments

- CHANGELOG.rst
- bleak/backends/dotnet/client.py
dotnet client descriptor now uses correct detach buffer function BleakDataWriter.detach_buffer() instead of BleakDataWriter.DetachBuffer()
Fix #402
> Dotnet client fixed misspelled detach buffer function

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
So far disconnect() method has cleared all services collection, but it
didn't reset client._services_resolved flag. This means that services
were not resolved after reconnecting to the same client.
Just clear client._services_resolved, which will allow to resolve
services properly with each subsequent reconnect.
> bluez: resolve services once again after reconnecting

- bleak/__version__.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/device.py
- bleak/backends/corebluetooth/scanner.py
In latest bleak version 0.10.0 the RSSI values of devices returned by `get_discovered_devices` are all zero.
This comes from `BLEDevice` class which has a `rssi=0` keyword argument default to zero. 
This PR updates this value with the real `RSSI` value.
@dlech I don't know if this is the best way to solve this, so feel free to change anything before merging 👍 
PD: Also for some reason bleak version in develop branch is still `0.9.1`, I guess this should be updated as well.
> Fix rssi values in BLE scanner

- examples/connect_by_bledevice.py
- examples/get_services.py
Fixes #413 
Output now looks like:
```
$ python examples/get_services.py
Services:
00001801-0000-1000-8000-00805f9b34fb: Generic Attribute Profile
00001800-0000-1000-8000-00805f9b34fb: Generic Access Profile
0000180a-0000-1000-8000-00805f9b34fb: Device Information
abbafd00-e56a-484c-b832-8b17cf6cbfe8: Unknown
ac2f0045-8182-4be5-91e0-2992e6b40ebb: Unknown
abbaff00-e56a-484c-b832-8b17cf6cbfe8: Unknown
0000fe2c-0000-1000-8000-00805f9b34fb: Google Inc.
0000fe26-0000-1000-8000-00805f9b34fb: Google Inc.
```
> Example scripts now print one service per line.

- CHANGELOG.rst
- bleak/__version__.py
- bleak/backends/dotnet/client.py
- examples/philips_hue.py
Added protection levels when trying to pair with devices in Windows backend. It works with ProtectionLevel = 2 (Encrypted) at least, which solves some problems, e.g. #405.
Also wrote a sample script for connecting to and controlling Philips Hue lamps, albeit only tested in Windows.
> Pairing improvement for .NET backend

- bleak/backends/bluezdbus/scanner.py
`set_scanning_filter` does not work in the current implementation.  This fix implements all of the proper varients for BlueZ 5.48.  There are more on the master branch for BlueZ, but I only implemented those in the docstring.
> Fixing set_scanning_filter

- CHANGELOG.rst
- bleak/__version__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/dotnet/client.py
- docs/troubleshooting.rst
* Keyword arguments to ``get_services`` method on ``BleakClient``.
* Keyword argument ``use_cached`` on .NET backend, to enable uncached reading of services, characteristics and descriptors in Windows.
Setting ``use_cached`` to ``True`` by default, since reading them from device noticably increased the connection time. Devices with mutable services are more rare than the opposite I think.
This might solve #429.
> Adding option to avoid using cached services in .NET backend.

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
The test in `bleak.backends.bluezdbus.client.py::connect::_services_resolved_callback` is quite obviously misplaced.
> Obviously misplaced code

- CHANGELOG.rst
- bleak/backends/bluezdbus/characteristic.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/service.py
- bleak/backends/bluezdbus/utils.py
- bleak/backends/characteristic.py
- bleak/backends/corebluetooth/characteristic.py
- bleak/backends/corebluetooth/descriptor.py
- bleak/backends/corebluetooth/service.py
- bleak/backends/descriptor.py
- bleak/backends/dotnet/characteristic.py
- bleak/backends/dotnet/descriptor.py
- bleak/backends/dotnet/service.py
- bleak/backends/service.py
- examples/service_explorer.py
Identifying Services by UUID is wrong, since a peripheral can have multiple services with the same UUID. The proper identifier should be the handle instead. From previously having thought the service handles was not present in the APIs that Bleak use, I have now done a depper investigation and foudn that I was wrong, they were there and they were quite easily obtained as well.
This should once and for all prevent the `This service is already present in this BleakGATTServiceCollection!` error from occuring for users.
Fixes #445 and #362.
This PR also removes all `__str__` methods from subclasses of `BleakGATT*` in favour of the ones in the abstract base classes.
> Changed Service identification to handles instead of UUID

- CHANGELOG.rst
- bleak/backends/device.py
Updated `BLEDevice` constructor to remove setting self.name to `Unknown` if not name. 
Updated `BLEDevice.__str__` conditional to check not self.name instead of equality to `Unknown` .
Updated second return statement in `BLEDevice.__str__` to use `self.name` or `Unknown`.
Updated changelog
> Fix for the 'Unknown' name in scan results on Windows 10. 

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/dotnet/client.py
- examples/async_callback_with_queue.py
- examples/sensortag.py
I have gotten a steady stream of questions in my mailbox about having async methods for notification callbacks. This time I had recently seen the [`asyncio.run_coroutine_threadsafe`](https://docs.python.org/3.7/library/asyncio-task.html#asyncio.run_coroutine_threadsafe) method and saw that it might just do the trick in a pretty simple fashion. This is a PR to get feedback on this idea and also testing and sounding boards for macOS.
- Added handling of async callbacks for Windows.
- Added handling of async callbacks for BlueZ.
- Added handling of async callbacks for Core Bluetooth.
> Having async methods as notification handlers

- bleak/backends/bluezdbus/client.py
This removes the call to stop_notify() in the cleanup code path in the BlueZ backend. This was causing an error message to always be logged when notifications were enabled and a device was disconnected.
As described in the code comment. This call is not necessary and can be removed.
Fixes: #472
(No changelog since this bug was introduced in changes since the previous release)
> BlueZ: Fixed stop_notify() error logged on device disconnect.

- CHANGELOG.rst
- docs/conf.py
This expects the module name rather than the package name, so we have to use an underscore instead of a dash.
> Fix linux_autodoc_mock_import in docs/conf.py

- CHANGELOG.rst
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/dotnet/scanner.py
- bleak/backends/scanner.py
- docs/scanning.rst
This adds a new `BleakScanner.discovered_devices` property to replace the `BleakScanner.get_discovered_devices()` async method.
A deprecation warning is added to `BleakScanner.get_discovered_devices()` and the documentation for that method.
Fixes #489
> Replace get_discovered_devices with discovered_devices

- examples/philips_hue.py
The Hue example is missing examples of how to use color. I pulled the logic from another repo on the conversion to the correct format and added a reference line for it. I also added my own repo since I am using this and may expand in the future.
The color characteristic is wrong, its 0005, not 0004, 0004 appears to be color temperature (soft-white / blue-white). I haven't played with this or I would of expanded on it, so I just left the line for anyone looking for it.
> Correct and improve Philips Hue example

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
When checking if device is already paired in `BleakClientBlueZDBus`
`pair()` method, result of call reading the Paired property
reply.body[0] is object type `dbus_next.signature.Variant` and always
evaluated to `True`, even if the actual value represented was `False`.
Test:
```python
>>> reply.body[0]
<dbus_next.signature.Variant ('b', False)>
>>> bool(reply.body[0])
True
>>> reply.body[0].value
False
>>> bool(reply.body[0].value)
False
```
Moreover, when setting the Trusted property, the following exception
was raised:
```plain
dbus_next.errors.SignatureBodyMismatchError: DBus VARIANT type "v"
must be Python type "Variant", got <class 'bool'>
```
> Fix read and set of D-Bus properties in BleakClientBlueZDBus.pair()

- CHANGELOG.rst
- bleak/backends/bluezdbus/utils.py
- bleak/exc.py
Converting `BleakDBusError` to string now adds detailed description of the
error, which can be very useful for debugging, as more than 12 different 
errors are reported under `org.bluez.Error.Failed` error name.
Instead of
```
bleak.exc.BleakDBusError: org.bluez.Error.Failed
```
one now gets
```
bleak.exc.BleakDBusError: org.bluez.Error.Failed (Operation failed with ATT error: 0x0e = Connection Rejected Due To Security Reasons)
```
Some details are less useful, as example
```
bleak.exc.BleakDBusError: org.bluez.Error.AuthenticationFailed
```
becomes
```
bleak.exc.BleakDBusError: org.bluez.Error.AuthenticationFailed (Authentication Failed)
```
But looking at more possible error codes and their details (majority
from BlueZ sources `gdbus/object.c` and `src/gatt-client.c`), it becomes
clear …
> Add error description to BleakDBusError in addition to error name

- bleak/backends/corebluetooth/CentralManagerDelegate.py
For some older devices the bluetooth stack does not support BLE.
The error message "Bluetooth device is turned off" can then be confusing, if on that device bluetooth is actually switched on (and working) but the actual problem is that BLE is not supported.
> During init() support raising a "BLE is unsupported"

- bleak/backends/winrt/scanner.py
This pull request addresses some minor issues I found while trying out the WinRT backend, as documented in #536. After some gentle ribbing from @dlech, I decided to roll these changes up into a pull request.
For me, these changes were sufficient to allow me to scan for a custom BLE device using the local name as a scan filter, connect to it, and interact with the characteristics.
I ended up making three changes:
1. Updating the WinRT backend to implement the `discovered_devices` property instead of the old `get_discovered_devices()` method.
2. Fixing an assertion in the UUID construction when the device has 128-bit service UUIDs.
3. Fixing a typo in the advertisement filter attribute of watcher objects
For reference, I was able to filter on the local name with a variant on the following …
> Fix minor WinRT backend bugs

- CHANGELOG.rst
- bleak/backends/corebluetooth/scanner.py
This fixes #448.
Also include a code cleanup in the same file while we are touching this.
> Fix missing delegate in BLEDevice metadata

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/dotnet/client.py
- bleak/backends/winrt/client.py
Adding a simple method to the macOS client to get the current ATT MTU size.
The ATT MTU size includes the ATT header, while CoreBluetooth returns the maximum ATT payload size, hence the +3 in the getMtuSize method.
> Adding mtu_size client

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
This is a regression from when we switched to dbus-next. It doesn't return the fds as part of the body but rather in a separate attribute.
See
- https://github.com/hbldh/bleak/discussions/531
- https://github.com/hbldh/bleak/pull/525#issuecomment-839353355
> Fixed write without response on BlueZ < 5.51.

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/dotnet/client.py
- bleak/backends/winrt/client.py
The write_gatt_char and write_gatt_descriptor methods allow for both a bytes and bytearray object. Typing did only allow for a bytearray.
> change typing on data parameter in `write_gatt_char` and `write_gatt_descriptor`

- bleak/backends/winrt/scanner.py
Update the WinRT branch to report RSSI using the standard `BLEDevice.rssi` field added in #390.
> Populate rssi field for WinRT backend

- bleak/backends/bluezdbus/client.py
- examples/mtu_size.py
BlueZ doesn't have a good way to get the negotiated MTU, but we can get it by abusing existing D-Bus methods.
Since the workaround is async and could cause unwanted side effects for some devices, it opt-in as seen in the example code.
> Add hack for getting MTU on BlueZ backend.

- CHANGELOG.rst
- bleak/backends/corebluetooth/PeripheralDelegate.py
Errors from CBPeripeheralDelegate calls were being raised in the asyncio
event loop, but not in the correct task. In order to reach the user's
code, the error has to be passed through the event to the user call that
is awaiting the event.
Without these changes, e.g. ATT errors sent by the peripheral caused
error messages to be printed, but since the event that the user's call
was waiting on was never set, the user's code was blocked.
The implementation was adapted from https://github.com/hbldh/bleak/pull/209
I have not been able to test with anything older than macOS Big Sur (11.4).
flake8, tox and pytest report loads of unrelated errors, but I did not see any
new errors from these changes.
Before you submit a pull …
> Fix propagation of CoreBluetooth errors

- CHANGELOG.rst
- bleak/__init__.py
Importing `bleak` on CI will fail if `bluetoothctl` is not installed. This adds a check for the CI environment variable that is set by default in many CI environments (e.g. GitHub Actions, Travis CI, etc.). Since we aren't sure that the value will be the same on all CI platforms, we just check for the presence of the variable. The check extends the same workaround that is already in place for building on readthedocs.org.
> Add CI environment variable check to import.

- CHANGELOG.rst
- bleak/backends/scanner.py
- examples/async_callback_with_queue.py
- examples/connect_by_bledevice.py
- examples/enable_notifications.py
- examples/get_services.py
- examples/philips_hue.py
- examples/scanner.py
- examples/scanner_byname.py
- examples/service_explorer.py
This change adds a new method `BleakScanner.find_device_by_filter(filterfunc)` that finds the first device that matches the filter function.
There's a new example `scanner_byname.py` that is similar to `scanner.py` but you specify the name of the BLE device you are looking for in stead of the address.
(I haven't merged the commits, in case you want to partially accept this).
> Discovery filter

- CHANGELOG.rst
- bleak/backends/corebluetooth/PeripheralDelegate.py
This fixes the `value` passed to the notification callback not being cast to `bytearray` like other backends.
Fixes #560
> Fixed notification value should be bytearray on CoreBluetooth.

- CHANGELOG.rst
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/scanner.py
- typings/Foundation/__init__.pyi
- typings/objc/__init__.py
This makes use of ObjC-style key-value observer to monitor the `isScanning` property on `CBCentralManager`. This allows us to avoid the polling wait.
Previously, the wait was only implemented when stopping scanning, so it is added to the start as well.
Also, the higher-level function is fixed to allow calling `stop()` multiple times without raising an error. This is needed since the
`stop()` method can be called by `__aexit__()` even if the scanner is already stopped.
> CoreBluetooth scan start/stop improvements

- CHANGELOG.rst
- bleak/backends/corebluetooth/PeripheralDelegate.py
In CoreBluetooth, there is no feedback for write without response, so we just have to send it and hope for the best. In this case we should not create a future since it gets registered with the event loop but it is never awaited.
Fixes #586
> CoreBluetooth: fix unawaited future for write without response

- CHANGELOG.rst
- bleak/backends/scanner.py
This PR just fixes a little bug where the timeout passed into `find_device_by_address()` method of `BleakScanner` wouldn't be passed into the `find_device_by_filter()` called later rendering the timeout parameter unused.
> Use timeout passed into find_device_by_address in BleakScanner implementation

- AUTHORS.rst
- CHANGELOG.rst
- bleak/backends/scanner.py
Fixed BleakClient ignoring the `adapter` kwarg. Fixes #607.
> BleakClient use adapter kwarg

- CHANGELOG.rst
- bleak/backends/winrt/client.py
We always use the "with result" variant of Windows API functions to get more information about failures. This was probably just overlooked when porting the Windows backend to WinRT.
Fixes #615.
> Use correct method when writing descriptor in WinRT backend.

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Avoid race in match removal and bus disconnection by keeping lock during cleanup.
fixes #603
3. The pull request should work for Python 3.6+ on the following platforms:
consider making several PRs …
> Lock bluez cleanup process

- CHANGELOG.rst
- bleak/backends/winrt/client.py
`BluetoothLEDevice.FromBluetoothAddressAsync()` can return null, so we need to handle this case. The link in the comment provides some insight in to what might cause this failure.
> winrt: improve error message when connecting fails

- CHANGELOG.rst
- bleak/backends/winrt/client.py
This changes the WinRT backend to use the GATT session status instead of the actual device connection status. Windows doesn't actually allow explicitly connecting and disconnecting devices. This is handled automatically in the background. So instead, we use the GATT session to act as the connection status. This could potentially fix some issues where devices disconnect briefly after initial connection and before enumerating services.
> winrt: use GATT session status

- bleak/backends/corebluetooth/PeripheralDelegate.py
Fixes the following exception:
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/Users/david/work/bleak/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 358, in did_disconnect_peripheral
callback()
File "/Users/david/work/bleak/bleak/backends/corebluetooth/client.py", line 105, in disconnect_callback
for future in self._delegate.futures():
File "/Users/david/work/bleak/bleak/backends/corebluetooth/PeripheralDelegate.py", line 77, in futures
if self._services_discovered_future
AttributeError: 'PeripheralDelegate' object has no attribute '_services_discovered_future'
Problem was introduced by commit …
> corebluetooth: fix crash on disconnect

- CHANGELOG.rst
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/p4android/defs.py
- bleak/backends/p4android/scanner.py
- bleak/backends/scanner.py
- bleak/backends/winrt/client.py
- bleak/backends/winrt/scanner.py
- examples/detection_callback.py
macOS has a bug (feature?) where advertising data is no longer received unless one or more service UUIDs are given in `scanForPeripheralsWithServices:options:`.
This implements a new kwarg on `BleakScanner` to allow users to provide such a list of UUIDs. This commit only implements it in the CoreBluetooth backend with other backends to follow.
If macOS 12 is detected and this kwarg is not given, an error will be logged explaining how to fix the problem.
Fixes #635.
> corebluetooth: work around macOS 12 scanner bug

- examples/detection_callback.py
On macos the service_uuids need to be filled. Main issue for
beginners is to retrieve some valid uuids. Instead of using an
external tool like nRF we could use predefined ones in bleak/uuids.
Implementation works with 128bit and 16bit UUIDs.
Related-to #635
Signed-off-by: Marc Koderer <marc@koderer.com>
> Use predefined service uuids

- Pipfile
- requirements_dev.txt
- setup.py
Apparently there are some security concerns about pytest-runner. We weren't using it anyway, so we can remove it.
> drop pytest-runner

- .github/workflows/build_and_test.yml
- .github/workflows/build_android.yml
The Android build is failing and I don't have time to fix it. This converts it to a manual trigger so that it doesn't cause pull requests to go red but keeps the job so we can fix it later.
> github: convert android build to manual trigger

- CHANGELOG.rst
- Pipfile
- requirements.txt
- setup.py
This removes the explicit apartment initialization that breaks apps that have already initialized a single threaded apartment.
Fixes: https://github.com/hbldh/bleak/issues/698
> requirements: bump bleak-winrt to v1.1.0

- CHANGELOG.rst
- bleak/uuids.py
LEGO has Powered Up Smart Hubs that communicate with BLE. This adds the UUIDs for the official LEGO firmware and 3rd-party Pybricks firmware.
> uuids: add LEGO UUIDs

- README.rst
- docs/scanning.rst
- docs/troubleshooting.rst
- docs/usage.rst
We frequently get bug reports about circular import errors. This is due to naming your script `bleak.py`. So put warnings  everywhere so hopefully people won't miss it.
Fixes: #729
Fixes: #704
Fixes: #515
> docs: warn against bleak.py

- CHANGELOG.rst
- bleak/backends/winrt/client.py
This fixes a regression caused by 3f26be6. When a `BLEDevice` is passed instead of a string, it tries to loop up a non-existent attribute.
Fixes: #731
> winrt: fix AttributeError in BleakClient.__init__()

- CHANGELOG.rst
- Pipfile
- requirements.txt
- setup.py
v1.1.0 was not statically linked against the MSVC runtime and would require users to manually install it to avoid an `ImportError`.
Fixes: https://github.com/hbldh/bleak/issues/741
> winrt: update bleak-winrt to v1.1.1

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
Commit 3f26be60c "winrt: combine adv data and scan rsp data" incorrectly assumed that `local_name` would return None instead of '' when no name was present in the advertising data. This changes the test to not strictly check for None.
Fixes: https://github.com/hbldh/bleak/issues/736
> winrt: fix name is 'Unknown'

- bleak/backends/corebluetooth/scanner.py
- setup.cfg
Based on further insights from https://github.com/hbldh/bleak/issues/720, we should be able to suppress this error if bleak is being used within a .app.
> Skip logging CoreBlueooth scanner error if running as .app

- CHANGELOG.rst
- bleak/backends/winrt/client.py
Added a local `DeviceInformation` object to make sure flags are updated to enable pairing and unpairing.
Solves #699
> Local device info object for pair/unpair

- docs/troubleshooting.rst
- Add information / tips to help with:
- Connection issues to multiple devices
- Pass more parameters to notify callback function
Fixes #754
> Add a Multiple Device Troubleshooting Section

- CHANGELOG.rst
- MANIFEST.in
This is needed for mypy to read the type signatures defined in the project, ref https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
There's also a note about needing `zip_safe=False`, but I'm not to familiar with setuptools so I didn't want to add that unless it's strictly required.
> Add py.typed file

- bleak/backends/service.py
This fixes a few type hints in bleak.backends.service and simplifies
some code by using implicit default values and avoiding unnecessary
else clauses.
> bleak/backends/service: fix type hints and simplify code

- CHANGELOG.rst
- bleak/backends/corebluetooth/PeripheralDelegate.py
Adjust read timeout with corebluetooth to 10s
5s would result in quite a few random failures with
HomeKit BLE devices because the device would have to
process a large dump of fragments which make it slow
to respond
Fixes https://github.com/Jc2k/aiohomekit/issues/111
Example of code that slows down the device with many
encrypted writes before waiting for a read
https://github.com/Jc2k/aiohomekit/blob/0e22b4e0a16d6b01da2e65bfce99fb01b4c1c7f3/aiohomekit/controller/ble/client.py#L117
> Adjust read timeout with corebluetooth to 10s

- AUTHORS.rst
- CHANGELOG.rst
- Pipfile
- bleak/assigned_numbers.py
- bleak/backends/bluezdbus/advertisement_monitor.py
- bleak/backends/bluezdbus/defs.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/bluezdbus/utils.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/p4android/scanner.py
- bleak/backends/scanner.py
- bleak/backends/winrt/scanner.py
- docs/scanning.rst
- examples/detection_callback.py
- examples/mtu_size.py
- requirements.txt
- requirements_dev.txt
- setup.py
This implements passive scanning in the BlueZ backend using the experimental [advertisement monitor api](https://github.com/bluez/bluez/blob/master/doc/advertisement-monitor-api.txt).
Fixes #606.
This PR also includes some improvements to the argument handling of the `BleakScanner` constructor that lays the groundwork for the new args required by this new feature. It also includes a new global BlueZ state manager which, in addition to making the passive scanning feature trivial to implement, will be useful in fixing other long-standing BlueZ issues.
There are a number of technical restrictions for using the BlueZ advertisement monitor api (I've tried to make useful error messages to guide users). The following should probably be added to the docs:
System requirements are BlueZ >= 5.56 and …
> Bluez advertisement watcher/passive scanning

- bleak/backends/bluezdbus/signals.py
Simple fix in documentation of method describing the error that could be raised.
> Fix documentation of raised error

- bleak/backends/bluezdbus/descriptor.py
Method documentation sentence should start with capital letter.
> Fix in method documentation

- bleak/backends/bluezdbus/client.py
Fix for method named to use to determine MTU Size as provided in warning for BlueZ backend.
There is actually no `_assign_mtu()` method at all in Bleak, while there is an `_acquire_mtu()` method that is supposed to determine the MTU Size on the BlueZ backend.
> Fix for method named to use to determine MTU Size

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
This adds a better error message when an adapter is missing on the BlueZ backend. Instead of getting a D-Bus method not found error, it will actually say what the real problem is - the adapter is not present.
Fixes #889.
> bluezdbus/manager: add adapter check and error

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
We have found that when doing passive scanning, some devices only send
one advertisement and then go to sleep for a while. BlueZ triggers
InterfacesAdded and InterfacesRemoved signals for these devices since
the sleep time is long enough for them to be considered no longer
present.
This caused advertisements to be missed since we were previously just
relying on PropertiesChanged signals with an RSSI change to determine
if a device is actually advertising.
By calling the callbacks on InterfacesAdded signals as well, we can
catch the very first and possibly only advertisement from these sorts
of devices.
> bluezdbus/manager: call advertisement callbacks from InterfacesAdded

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/manager.py
This fixes a number of bugs by moving the `BleakClient` state management to the new global BlueZ manager object.
- Calling "GetManagedObjects" each time we connected caused performance  issues. Fixes #500.
- Calling "ConnectDevice" didn't work as expected and has been removed.  Fixes #806.
- BleakClient didn't handle "InterfacesRemoved" which resulted in an invalid service dictionary in some cases. Fixes #882.
> bluez/client: move state management to global BlueZ manager

- docs/troubleshooting.rst
old link was getting 404 error
> docs/troubleshooting: fix windows BTP link

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
Fixes logging-format-interpolation (W1202)
Fixes `__repr__` being called and thrown away
> Make callback logging lazy

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
```
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/bluetooth/__init__.py", line 253, in async_setup_entry
await manager.async_start(
File "/usr/src/homeassistant/homeassistant/components/bluetooth/__init__.py", line 343, in async_start
await self.scanner.start()  # type: ignore[no-untyped-call]
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 128, in start
manager = await get_global_bluez_manager()
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 808, in get_global_bluez_manager
await instance.async_init()
File …
```
> Fix disconnect in the global BlueZ manager

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Fixes
```
Logger: bleak.backends.bluezdbus.client
Source: components/switchbot/cover.py:94
First occurred: 10:36:23 (1 occurrences)
Last logged: 10:36:23
Failed to cancel connection (/org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX): 'NoneType' object has no attribute 'call'
```
> Handle the race in the BlueZ D-Bus backend where the device disconnects during the connection process

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
When the dbus socket gets disconnected from dbus, we cannot
reuse the connection because dbus-next finalize will remove
the underlying fds
Fixes
```
2022-08-02 09:29:00.722 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bluetooth for bluetooth
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/bluetooth/__init__.py", line 253, in async_setup_entry
await manager.async_start(
File "/usr/src/homeassistant/homeassistant/components/bluetooth/__init__.py", line 343, in async_start
await self.scanner.start()  # type: ignore[no-untyped-call]
File …
```
> Avoid reusing the MessageBus in the manager

- CHANGELOG.rst
- bleak/backends/corebluetooth/PeripheralDelegate.py
> Adjust default timeout for ``read_gatt_char()`` with CoreBluetooth to 20s

- CHANGELOG.rst
- bleak/backends/device.py
- bleak/backends/service.py
In Python 3, we don't need to explicitly inherit from object.
> remove explicit inheritance from object

- CHANGELOG.rst
- bleak/backends/bluezdbus/characteristic.py
- bleak/backends/bluezdbus/defs.py
- bleak/backends/bluezdbus/descriptor.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/scanner.py
Fixes #927.
See commit message for details.
@bdraco can you test and see if this actually makes a measurable difference in performance?
> Bluez: improve get services performance

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
This filter was originally added to get the same behavior as macOS. However macOS has changed so we receive duplicate events even when filter duplicates is enabled. At one time, we had a similar filter in place on Windows as well, but that seems to have been removed. So with this change, all OSes are having the same behavoir again.
This also has a practical use case in that it allows us to get RSSI change events to allow making proper user interfaces that show changing RSSI while scanning devices.
> BlueZ: don't ignore RSSI change in detection callbacks

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/scanner.py
This fixes a regression introduced in v0.15 where device removed from BlueZ while scanning were no longer removed from this list of discovered devices. This caused the `discovered_devices` property to return devices that could no longer be connected to by BlueZ since they were removed.
Fixes #942.
> BlueZ: fix removed devices included in discovered_devices

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
It is possible for get_services() to raise an exception, e.g. if external code cancels the task. If this happens, we need to be sure
that the device disconnects so the BlueZClient is in a consistent state (if the connect() method raises and exception, is is expected that the device will not be connected).
To fix this, we can just move the call to get_services() inside of the existing try block that will disconnect on any exception, then reraise the exception.
Fixes #951.
> BlueZ: fix not disconnecting if get_services() throws during connect

- CHANGELOG.rst
- bleak/backends/winrt/client.py
Since the following error occurred when connecting, set the MTU to the default 20 to avoid it.
`AttributeError: 'NoneType' object has no attribute 'max_pdu_size'`
```
File "C:\Users\saido\scoop\apps\python39\current\lib\site-packages\bleak\backends\winrt\client.py", line 331, in connect
await self.get_services()
File "C:\Users\saido\scoop\apps\python39\current\lib\site-packages\bleak\backends\winrt\client.py", line 547, in get_services
characteristic, self._session.max_pdu_size - 3
AttributeError: 'NoneType' object has no attribute 'max_pdu_size'
```
Tested by Python 3.9 on Windows 11.
> Fix `get_services()`  fails because no GattSession

- CHANGELOG.rst
- bleak/backends/winrt/client.py
This changes the disconnect timeout on the WinRT backend to 120s.
Sometimes it can take up to a minute for Windows to actually close
the GATT session/disconnect the device. This behavior is also seen
in other apps, like WebBluetooth in Chrome. Furthermore, the device
remains connected even after the app is closed, so clearly this is
an issue with the Windows Bluetooth stack and not something that
can be fixed in userspace code.
Fixes #807.
> backends/winrt/client: extend disconnect timeout

- CHANGELOG.rst
- bleak/exc.py
We are decoding the ATT error message number to a string. This was
using the wrong lookup table for the messages.
`PROTOCOL_ERROR_CODES` matches `BT_ATT_ERROR_*` in the BlueZ source.
> exc: fix BlueZ ATT error messages

- .readthedocs.yml
- docs/requirements.txt
- poetry.lock
- pyproject.toml
This fixes build docs on Python >=3.10.
Also update readthedocs.yml with new requirements.txt to fix failing builds.
> docs: update sphinx to latest version

- .github/workflows/format_and_lint.yml
- examples/kivy/main.py
This fixes all instances of flake8 E402 and enables CI to fail on future instances of this error.
> flake8: fix E402 and enable in CI

- .github/workflows/build_and_test.yml
Poetry seems to be picking up the wrong Python version when creating the virtual environment, so specify it explicitly using:
poetry env use pythonX.Y
> github: fix virtual env python version

- CHANGELOG.rst
- bleak/backends/bluezdbus/advertisement_monitor.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/bluezdbus/signals.py
- bleak/backends/bluezdbus/utils.py
- docs/conf.py
- poetry.lock
- pyproject.toml
Removes workaround since `.disconnect()` now closes the socket and fixes the leak.
> Switch from dbus_next to dbus_fast

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/manager.py
> Handle a device already being connected with the BlueZ Dbus backend

- CHANGELOG.rst
- bleak/backends/bluezdbus/characteristic.py
- bleak/backends/characteristic.py
- bleak/backends/corebluetooth/characteristic.py
- bleak/backends/p4android/characteristic.py
- bleak/backends/winrt/characteristic.py
The `properties` and `descriptors` properties had inconsistent return types between backends. This makes them consistent in all backends.
> backends/characteristic: fix inconsistent property types

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
Fixes #996
```
File "/usr/local/lib/python3.10/site-packages/dbus_fast/message_bus.py", line 736, in _process_message
result = handler(msg)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 710, in _parse_msg
del self._properties[obj_path][interface]
KeyError: '/org/bluez/hci0/dev_00_06_80_08_D2_95'
```
> Handle device being removed before GetManagedObjects returns

- CHANGELOG.rst
- bleak/backends/winrt/client.py
Hello,
this PR updates the BleakClientWinRT to use f-strings instead of .format function and lazy formatting for logger calls.
It also removes the _pairing_statuses  and _unpairing_statuses objects which contained a bit strange subset of the corresponding enums but skipping all values that contain an underscore. Instead of them DevicePairingResultStatus(value).name is used for logging the values.
> updated logging to lazy version and replaced format by f-string for BleakClientWinRT

- CHANGELOG.rst
- bleak/backends/winrt/client.py
It is possible that `self._session` is set to `None` when `max_pdu_size_changed_handler` is called. So we can use the `sender` arg instead to avoid a possible `AttributeError`.
Fixes #998.
> backends/winrt/client: fix crash in max_pdu_size_changed_handler

- bleak/backends/winrt/characteristic.py
> backends/winrt/characteristic: remove unused import

- .github/workflows/format_and_lint.yml
- bleak/__init__.py
The `# noqa: F401` directives were on the wrong line and not picked up by flake8. This moves them to correct line and also allows us to use the main flake8 config in CI since all errors are now fixed.
> __init__: fix noqa line

- CHANGELOG.rst
- bleak/__init__.py
- examples/disconnect_callback.py
- examples/discover.py
The discover() function was removed from the docs and was supposed to be deprecated in v0.13.0, but it didn't get a proper warning and was still used in some examples.
This removes it from the examples and adds a warning so that it can eventually be removed.
> deprecate discover() function

- CHANGELOG.rst
- pyproject.toml
Signatures of methods haven't changed since 3.0 for use cases in bleak.  Relaxing of the dependency will allow using prebuilt version of async-timeout on OpenWrt 21.03 which has version 3.0.1
> Relax async-timeout version

- CHANGELOG.rst
- bleak/backends/winrt/client.py
This is a alternative approach to https://github.com/hbldh/bleak/pull/1002
Calling unpair when not connected should remove all device information from the OS.
This also relates to issue https://github.com/hbldh/bleak/issues/309
> allow unpair without being connected on WinRT backend

- CHANGELOG.rst
- bleak/backends/scanner.py
0 is a valid value for `tx_power`, so we can't use a falsy check and need to check for None instead.
> backends/scanner: fix tx_power missing in __repr__ when 0

- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/winrt/client.py
0150ef3 broke implicit scanning because some methods were moved from the backends to the new top-level class.
This fixes the issue by using the new backends kwarg of the scanner to pass the matching scanner backend to the client. This also revealed a bug in the backend kwarg implementation that is now fixed.
> backends: fix implicit scanning when connecting

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/characteristic.py
- bleak/backends/winrt/client.py
- docs/troubleshooting.rst
- examples/async_callback_with_queue.py
- examples/enable_notifications.py
- examples/sensortag.py
- examples/two_devices.py
- examples/uart_service.py
Fixes #759. 
See commit messages and the issue for details.
> Notify callback rework

- bleak/__init__.py
- bleak/backends/client.py
- docs/api/client.rst
This was missed in #982 since BaseBleakClient didn't have an abstract property for this.
This adds the base abstract property to the backends, fixes the missing property in BleakClient client and adds it to the documentation.
cc @bdraco
> BleakClient: fix missing mtu_size property

- .github/workflows/build_and_test.yml
- CHANGELOG.rst
- poetry.lock
- pyproject.toml
In theory, older versions of Bleak should also work with Python 3.11 as long as any binary dependencies are available for that version.
This just makes the support official and updates the dependencies to ones that include binary wheels for Python 3.11.
> add support for Python 3.11

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
- docs/backends/linux.rst
Alternative to #1031. Avoids "got Future <Future pending> attached to a different loop" if Bleak instances with BlueZ backend are constructed in context of more than one event loop (for example, in default configuration of [pytest-asyncio](https://pypi.org/project/pytest-asyncio/)).
Also enables parallel access to Bleak instances from multiple event loops, provided the same Bleak object is not shared between two event loops. Each backend manager instance establishes an independent dbus connection with a unique dbus address.
Some quick code that demonstrates using Bleak in parallel from multiple threads (and therefore multiple event loops):
<details>
```python
import asyncio
import logging
from logging import getLogger, getLevelName, Formatter, StreamHandler
import threading
import time …
```
> bluez: Create a bluez manager instance per-event-loop

- CHANGELOG.rst
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- docs/troubleshooting.rst
If Bleak is run in a terminal app on macOS that has the permission for Bluetooth disabled, the CentralManager state will return unauthorized.
Previously, this raised the same error as when Bluetooth is not powered which is misleading. This adds a new error message for the unauthorized case.
Issue: https://github.com/hbldh/bleak/discussions/1016
> backends/corebluetooth: better error message for unauthorized

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/device.py
- bleak/backends/winrt/client.py
- bleak/exc.py
This is a first draft for BleakDeviceNotFoundError as discussed in https://github.com/hbldh/bleak/issues/527
> added BleakDeviceNotFoundError

- CHANGELOG.rst
- bleak/backends/winrt/client.py
This catches a possible OSError when max_pdu_size_changed_handler is called after the GATT session ends. It can safely be ignored.
Fixes #1039.
> winrt/client: handle exception in max_pdu_size_changed_handler

- bleak/__init__.py
This was broken in 825df5dcdcdc234edcd7b33086056d7edc198916.
Fixes #1038.
> fix deprecated discover method

- docs/api/scanner.rst
The example only works for me when adding the async to the main() function, otherwise i get this error:
```
async with BleakScanner(callback) as scanner:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'async with' outside async function
```
> docs: add async keyword to function

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/bluezdbus/utils.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/device.py
- bleak/backends/p4android/scanner.py
- bleak/backends/p4android/utils.py
- bleak/backends/scanner.py
- bleak/backends/winrt/scanner.py
- docs/api/scanner.rst
- examples/detection_callback.py
- examples/discover.py
- examples/kivy/main.py
* Performance improvements for keeping track of discovered devices.
* New property to get advertisement data along with discovered devices.
* Adds `rssi` attribute to `AdvertisemntData`
Additional details in the commit messages.
> Discovered devices improvements

- bleak/backends/bluezdbus/manager.py
Receiving advertisements is a hot path in the code. We can improve performance by avoiding using startswith. In this case we conveniently already have the adapter path available as a D-Bus property, so we can use that instead.
Also drop comment while we are touching this since deep copy wouldn't actually make much of a difference since the dictionary value should be treated as immutable already.
> backends/bluezdbus/manager: replace startswith in hot path

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Operates by calling RemoveDevice on the Adapter object, which can be done regardless of the device's connection status.
If the device is connected then calling this method will cause Bluez to disconnect. Calling this method will also cause Bluez to delete any bonding information and GATT attribute cache.
As noted in the previous version of this function, there doesn't seem to be a more direct way to unpair a device in Bluez. It's possible to set the Trusted parameter (readwrite) on a Device object, but not the Paired parameter.
> bluez: Implement unpair() method

- bleak/__init__.py
Minor clarifications added to the docstrings, as picked up from #904. It turns out most modifications there are no longer relevant because of the separation of the backend objects.
> Minimal documentation additions

- CHANGELOG.rst
- bleak/backends/winrt/client.py
We can get an access denied error for services returned before a services changed event. This handles services changed events that are received while attempting to get services. Hopefully, this is the only time this event is received in most cases.
Fixes #1061.
> backends/winrt/client: retry getting services if services changed event occurs

- bleak/backends/bluezdbus/scanner.py
This adds docs based on the BlueZ D-Bus API docs with additional comments for Bleak usage.
Related discussion: https://github.com/hbldh/bleak/issues/1065
> backends/bluezdbus/scanner: document BlueZDiscoveryFilters

- CHANGELOG.rst
- bleak/backends/p4android/scanner.py
In #1047, the call to getRssi() was broken by using the wrong object.
This fixes the mistake.
Fixes #1085.
> backends/p4android/scanner: fix crash when getting rssi

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
If a device disconnects while waiting for the services to be discovered, the manager will wait forever.
This commit fixes that by introducing a context to the _wait_condition method with an exception on disconnect.
> backends/bluezdbus/manager: Cancel the discovery on disconnect to avoid a timeout

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
The transmit power property of the advertising data was added in Windows
build 19041, so we need a fallback for older versions of Windows.
Fixes hbldh/bleak#1094
> winrt:: fix tx power compatibility

- .github/workflows/build_and_test.yml
Python 3.11 has been released so we no longer need the RC version.
> github: drop rc.2 from Python 3.11

- .github/workflows/build_and_test.yml
- .github/workflows/build_android.yml
- .github/workflows/format_and_lint.yml
- .github/workflows/pypi-publish.yml
Older versions are showing deprecation warnings because they use nodejs v12.
> github: bump actions versions

- CHANGELOG.rst
- bleak/backends/winrt/client.py
Python 3.11 crashes on Windows when connecting to a device:
File "C:\Users\david\Documents\GitHub\Pybricks\bleak\examples\service_explorer.py", line 64, in <module>
asyncio.run(main(sys.argv[1] if len(sys.argv) == 2 else ADDRESS))
File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File …
> winrt/client: fix crash when getting services

- CHANGELOG.rst
- bleak/backends/winrt/client.py
This changes the cache mode when getting services after a ServicesChanged event in the WinRT backend. This matches the recommendation of the docs.
https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.gattserviceschanged?view=winrt-20348
> winrt/client: change get services retry cache mode

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
Apparently, BlueZ will sometimes request to remove properties that were not set in the first place.
Fixes: #1107
> bluezdbus/manager: ignore KeyError when properties removed

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/corebluetooth/CentralManagerDelegate.py
- bleak/backends/corebluetooth/PeripheralDelegate.py
- bleak/backends/p4android/scanner.py
- bleak/backends/winrt/client.py
- poetry.lock
- pyproject.toml
Python 3.11 introduced a new `asyncio.timeout()` method that can be used instead of the `async_timeout` package.
> pyproject: drop async-timeout dependency on Python >= 3.11

- CHANGELOG.rst
- bleak/backends/device.py
We have thousands of these floating around in memory so it helps a bit for the RPI3b users.
Not done for `AdvertisementData` since `NamedTuple` already uses `__slots__` under the hood
> Reduce memory usage of BLEDevice with __slots__

- CHANGELOG.rst
- bleak/backends/winrt/client.py
- pyproject.toml
There were a number of issues with getting services not being restarted properly when a services changed event occurred. Cancellation wasn't handled properly in FutureLike and it wasn't used in enough places.
Now, the entire `get_services()` method is restarted when an event is received instead of only `self._requester.get_gatt_services_async()`.
> winrt/client: fix issues with getting services

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/client.py
Instead of using `_services_resolved: bool` and direct access to `services: BleakGATTServiceCollection` collection, this PR changes it to property with additional check whether services were actually discovered - they shall be before `connect()` returns.
> Instantiate BaseBleakClient.services collection only after service discovery

- CHANGELOG.rst
- bleak/__init__.py
This adds `%(threadName)s` to `FORMAT` passed to `logging.basicConfig()` when `BLEAK_LOGGING` is used. This can be useful to debug OS callbacks on background threads.
> bleak: include %(threadName)s in BLEAK_LOGGING

- CHANGELOG.rst
- examples/async_callback_with_queue.py
- examples/detection_callback.py
- examples/disconnect_callback.py
- examples/enable_notifications.py
- examples/service_explorer.py
Added a debug flag to all applicable examples that enables DEBUG level logging instead of default INFO level.
The flag can be called with either `-d` or `--debug`.
> Examples: added debug flag

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
When stopping scanning, we don't want to raise errors if we can be sure that scanning is in fact stopped.
`org.bluez.Error.NotReady` can be triggered if the Bluetooth adapter is turned off after scanning started, in which case we know that it is not scanning, so it is safe to ignore this error.
> bluezdbus/manager: suppress org.bluez.Error.NotReady when stopping scanner

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
When Bluetooth is disabled on Windows, we will never get the `BluetoothLEAdvertisementWatcher.Stopped` event from the WinRT API.
We can work around this by checking the status of the watcher to see if we can expect an event.
> winrt/scanner: fix stop hanging when Bluetooth disabled

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Sometimes the exception on connect is raised so early that the disconnect monitor task does not get the disconnect event set because the on_connected_changed callback is already unregistered and the task stays in pending state causing asyncio to throw an exception:
Task was destroyed but it is pending!
> bluezdbus/client: Make sure the disconnect monitor task is properly cancelled

- bleak/__init__.py
The type of the first argument to the callback changed from `int` to `BleakGATTCharacteristic` in 0.18.0. The code example was still type hinting it as an int.
I have added an import statement for `BleakGATTCharacteristic`, to make the code runnable, but I'm not sure if it should be omitted for clarity/readability/minimize confusion (since type hinting is optional). Feel free to delete that line if you prefer
> docs: Change code example for BleakClient.start_notify callback

- CHANGELOG.rst
- bleak/backends/winrt/client.py
If `get_servcies()` is cancelled or otherwise raises an error, the WinRT service objects need to be disposed by calling `close()`. Otherwise, it is going to cause problems for the Windows Bluetooth stack.
> winrt/client: fix leaking service objects

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/winrt/scanner.py
This removes the logic that skips the detection callback when expecting a scan response. It is valid for devices to broadcast ADV_IND but not respond to a SCAN_REQ (there is no flag that means connectable but not scannable so ADV_IND is the only choice in this case).
Fixes: https://github.com/hbldh/bleak/issues/1211
> winrt/scanner: drop waiting for matching scan rsp

- CHANGELOG.rst
- bleak/backends/corebluetooth/CentralManagerDelegate.py
Since the init() method can raise an exception before registering the observer, attempting to unregister the observer will fail with IndexError. We can safely ignore this error.
Fixes: https://github.com/hbldh/bleak/issues/1219
> backends/corebluetooth/CentralManagerDelegate: fix unhandled exception in __del__

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Since BlueZ 6.62, BlueZ has a new connection error "le-connection-abort-by-local" that is seen quite frequently, particularly when there are many BLE devices in the area.
Reconnecting immediately after receiving this error is generally successful, so we add an automatic retry in the BleakClient.
This is a bit tricky because the device does actually connect in this case and we receive D-Bus property changes indicating this, so we have to be careful about waiting for the disconnect event before trying again.
Fixes: https://github.com/hbldh/bleak/issues/1220
> bluezdbus/client: add retry on le-connection-abort-by-local

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/client.py
Since reworking to have a common top-level `BleakClient` class, the `disconnected_callback` function was called with the backend object rather than the top-level `BleakClient` object.
This fixes the mistake by using functools.partial to bind the top-level object to the function and eliminates the need to pass an argument in the backends.
> bleak: fix disconnected_callback arg

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Calling "ReadValue" and "WriteValue" on both characteristics and descriptors can fail will "org.bluez.Error.InProgress" if another read or write is currently in progress. This can be a problem if tasks or called in parallel or if a task is cancelled.
Instead of making users manually implement a retry, we can do it for them.
> backends/bluezdbus/client: retry on InProgress

- CHANGELOG.rst
- bleak/backends/winrt/client.py
As described in https://github.com/hbldh/bleak/issues/1280, it is possible for a session to be closed then activated again while getting services. This will cause an OSError because the closed event triggers the disconnect cleanup code, then trying to use the session after that fails because it has been closed.
This works around the problem by disabling the disconnect cleanup code until the connect method has returned successfully. If the connect method raises an exception, it handles cleanup already so the cleanup code in the session status event handler never gets called in this case.
> winrt/client: ignore session closed event during connect

- CHANGELOG.rst
- bleak/backends/winrt/client.py
The error messages were reporting something like:
<_bleak_winrt_Windows_Devices_Bluetooth_GenericAttributeProfile.GattDeviceService object at 0x00000206F9189750>
This is the repr of the service object which isn't very useful. Change the error message to include some useful identification properties instead.
> backends/winrt/client: improve get_services() error messages

- CHANGELOG.rst
- bleak/backends/winrt/client.py
We had a hard-coded list of services know to return an access denied error when attempting to enumerate characteristics. However, since we don't know Windows internals, the list was not exhaustive and it could also change in the future.
Instead, we can just check for the access denied error and skip any service that returns that error which should also handle additional services we don't know about yet.
Fixes: https://github.com/hbldh/bleak/issues/1291
> backends/winrt/client: handle arbitrary access denied

- CHANGELOG.rst
- bleak/uuids.py
- tests/test_uuid.py
3. The pull request should work for Python 3.7+ on the following platforms:
5. Feel free to add your name as a contributor to the `AUTHORS.rst` file!
> Added support for 32bit UUID's added in 4.1 of the Bluetooth spec

- CHANGELOG.rst
- bleak/backends/scanner.py
Function `register_detection_callback()` of `BaseBleakScanner` ensures that `_callback` is a synchronous function, so change its typing accordingly.
Additionally, passing `Awaitable` to `asyncio.create_task()` results in warning:
>  Unexpected type(s): (Awaitable[None] | None)
>  Possible type(s): (Generator[Any, None, Any] | Coroutine)
Every coroutine is an awaitable, but not every awaitable is a coroutine, so change the `AdvertisementDataFilter` type accordingly.
---
Not sure if this needs an entry in `CHANGELOG.rst` as it does not affect runtime functionality in any way?
> backends/scanner: Fix typing for callback

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/p4android/scanner.py
- bleak/backends/scanner.py
- bleak/backends/winrt/scanner.py
We are considering adding an async iterator that can be used to handle advertisement data as it is received. It will be trivial for users to create multiple parallel iterators, so instead of disallowing it, this prepares the way to allow multiple simultaneous subscribers.
> backends: allow multiple advertisement callbacks per scanner

- examples/two_devices.py
This fixes several issues with the implementation. Notably, on Linux trying to scan and connect to two devices at the same time results in:
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
This is worked around by using an asyncio.Lock to ensure only one scan and connect is called at a time.
Fixes: https://github.com/hbldh/bleak/issues/1036
Also fixes error due to main() not being a coroutine:
ValueError: a coroutine was expected, got <_GatheringFuture pending>
Fixes: https://github.com/hbldh/bleak/issues/1288
Finally, command line args are added to make it easy to run the example without modifying the code.
> examples/two_devices: fix example

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/client.py
- examples/mtu_size.py
- examples/philips_hue.py
- examples/sensortag.py
- examples/uart_service.py
Previously, some backends would select the "best" response type based on the reported characteristics while some did not. For the ones that didn't, it was a commonly reported issue for the write to not work.
This adds a recommendation to the docs to always be explicit about the requested response type and moves the common logic for picking the "best" type in the default case to the `BleakClient` class to avoid duplicated code.
The logic is simplified to prefer a write with response if available and no longer reports a warning for devices that don't properly specify properties (since it would create much noise with many writes).
> BleakClient.write_gatt_char: change handling of default response

- CHANGELOG.rst
- bleak/__init__.py
- docs/api/scanner.rst
- examples/scan_iterator.py
> Enable using `BleakScanner()` as an async iterator (async for), combining detection_callback and filtering functionality. `BleakScanner().devices()` method has the same functionality with option to provide timeout.
I noticed that almost every time I use `bleak`, one of the first things is to create scanner method which combines `discover()` and `find_device_by_filter()` functionality "in concurrent fashion", without the need of using callbacks and queue. This enables reporting scanned devices immediately while giving all the filtering flexibility, even when scanning for multiple devices with different filters.
> BleakScanner: Add async iterator scanning capability

- CHANGELOG.rst
- bleak/backends/bluezdbus/advertisement_monitor.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/bluezdbus/manager.py
- Switch usage of f-strings for log message formatting
- Guard expensive loggers with isEnableFor
https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html
Note: there are more of these. I only fixed the obvious ones and the ones that showed up in the profile (DeviceFound is red hot in the profile)
> Defer formatting for expensive debug logging

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
Alternative to #1329 and #1377.
@bdraco could you please take a look?
The issue addressed by #1377 seems more widespread, so I took it a bit farther to make sure it is fixed in all public functions (first commit).
Instead of synthesizing a `"Connected"` property change as proposed in #1329, here I have opted to just add a 3rd race condition on `"InterfacesRemoved"` when waiting for services to be resolved (second commit).
> fix BlueZ wait condition disconnect race

- AUTHORS.rst
- CHANGELOG.rst
- bleak/backends/p4android/recipes/bleak/__init__.py
- bleak/backends/p4android/recipes/bleak/fix_setup.py
- examples/kivy/README.md
- examples/kivy/buildozer.spec
Update of bleak on android  and the android kivy example
When trying to build my app with bleak, the android kivy example seemed out of date.
**Commmit: 51b277ee3fce9d7f6fa77579e3371b5fdcaa2045 :**
-  'async-timeout' was missing as a requirement in the buildozer.spec file. Fixes https://github.com/hbldh/bleak/issues/1184 ?
- 'BLUETOOTH_SCAN' and 'BLUETOOTH_CONNECT' permissions were missing in buildoze.spec file
- android.arch is deprecated, android.archs is preferred now
- updated armeabi-v7a to arm64-v8a as default architecture
**Commit:  17afc9553d2dbc7b41d4185dbb4c13fc25f7ab4e :**
- The bleak recipe was not working, this had two issues:
1. The recipe was quite project directory structure dependant. This works for the example, but not for your own …
> Update of bleak on android and the android kivy example

- CHANGELOG.rst
- bleak/backends/winrt/client.py
It appears that GattDeviceService.Close() can hang forever under
certain circumstances.  This change adds a 0.1 second delay before
closing services to see if that helps.
Fixes: https://github.com/hbldh/bleak/issues/1359
> backends/winrt/client.py: Add delay before closing services.

- bleak/backends/winrt/client.py
- docs/conf.py
WinError does the same thing and is a bit more straight forward.
> backends/winrt/client.py: drop use of pythonapi

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
Looks like a new release will be needed as well to unblock https://github.com/home-assistant/core/pull/99894
> Loosen dbus-fast pin to allow for dbus-fast 2.0

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/client.py
- bleak/exc.py
Add `BleakCharacteristicNotFoundError` which is raised if a device does not support a characteristic
It's not uncommon for devices to change its set of supported characteristics, for example during an initial setup.
Without a specialized exception class it's tricky to detect when this happens.
> Add BleakCharacteristicNotFoundError

- AUTHORS.rst
- CHANGELOG.rst
- bleak/__init__.py
Fixes #1487 in the simplest way, according to https://peps.python.org/pep-0692/#required-and-non-required-keys.  This has the effect of making the `BleakScanner` `ExtraArgs` optional instead of required.
For reference:
```python
class ExtraArgs(TypedDict):
"""
Keyword args from :class:`~bleak.BleakScanner` that can be passed to
other convenience methods.
"""
service_uuids: List[str]
"""
Optional list of service UUIDs to filter on. Only advertisements
containing this advertising data will be received. Required on
macOS >= 12.0, < 12.3 (unless you create an app with ``py2app``).
"""
scanning_mode: Literal["active", "passive"]
"""
Set to ``"passive"`` to avoid the ``"active"`` scanning mode.
Passive scanning is not supported on macOS! Will raise
:class:`BleakError` if set to ``"passive"`` on …
```
> fix: incorrect mypy diagnosis of Unpack[ExtraArgs].

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
Fixes https://github.com/hbldh/bleak/issues/1507
> Improve error handling when a device is not present in BlueZ

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
The _wait_removed method registers the "InterfacesRemoved" callback on the adapter path of the device without checking which object was removed when called.
This means that any removed interface while a connection is being established can cause the _wait_removed to complete and cancel the connection.
This commit simply checks that the callback is for the proper device object path.
Fixes #1489
> Fix _wait_removed completion on invalid object path

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
This adds a check to give a useful error message instead of silently failing if Bluetooth is off.
> WinRT: check scanner for abort

- CHANGELOG.rst
- bleak/backends/p4android/scanner.py
This was using the advertisement received signal strength indicator instead of the transmitted power level. This is now fixed.
Fixes: https://github.com/hbldh/bleak/issues/1532
> backends/p4android: fix using wrong tx_power value

- CHANGELOG.rst
- bleak/backends/service.py
This fixes 4-character UUIDs causing BleakCharacteristicNotFoundError instead of being properly resolved.
Fixes: https://github.com/hbldh/bleak/issues/1498
> backends/service: normalize UUIDs in get_characteristic()

- CHANGELOG.rst
- bleak/backends/winrt/client.py
- examples/service_explorer.py
Users have reported that the max pdu size was wrong on some devices. This was happening because the max_pdu_size_changed event was happeing after the get_services() call returned.
This adds an event to wait for the max_pdu_size_changed event to happen and updates the characteristics in the service dictionary after the fact to ensure they have the correct value.
The service_explorer example is also updated to show the value to help with future troubleshooting.
Fixes: https://github.com/hbldh/bleak/issues/1497
> backends/winrt: fix max pdu update race

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
This updates to the stable release of winrt, which is now 2.0.1. This has the side effect of fixing import errors on systems where the required Visual C++ redistributable is not installed.
Fixes: https://github.com/hbldh/bleak/issues/1529
> pyproject: update winrt depedencies

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
- bleak/backends/winrt/util.py
- docs/troubleshooting.rst
The pywin32-related packages will implicitly set the threading model to STA when imported. Since Bleak is using WinRT for async methods and we don't have a Windows event loop running, we need to let users know that Bleak is not going to work in this case.
Also add a utility function and troubleshooting docs to provide a workaround for this issue.
Fixes: https://github.com/hbldh/bleak/issues/1132
> backends/winrt: raise exception when trying to scan with STA

- CHANGELOG.rst
- bleak/backends/scanner.py
- bleak/backends/winrt/scanner.py
It was noted that on Linux, if another app was scanning at the same time, BlueZ would trigger RSSI changes for all devices, even if they they didn't match the service_uuids filter.
This change ensures that we always filter by service_uuids, even if the OS isn't doing it for us.
On Windows, the OS wasn't filtering for us anyway, so we can just move that code to the shared call_detection_callbacks() so that all backends will make use of it.
Fixes: https://github.com/hbldh/bleak/issues/1534
> backends/scanner: always filter by service_uuids

- CHANGELOG.rst
- bleak/backends/winrt/util.py
- docs/troubleshooting.rst
We had lots of users reporting issues with the WinRT backend hanging forever when trying to connect to a device. This was happening because some other imported library was initializing the the main thread to STA which caused some async callback to never be called.
To work around this, we added a check to make sure the main thread is set to MTA rather than STA. Unfortunately, in cases where there is a graphical user interface library being used AND that library is properly interated with asynco so that Bleak runs in the main thread rather than in a background thread, the thread type does need to be STA for the GUI to work. So in those very specific conditions, we need to not raise an exception.
We don't know of a way to detect this automatically, so we added a new utility function …
> backends.winrt: add allow_sta() utility function

- CHANGELOG.rst
- bleak/backends/winrt/util.py
- docs/troubleshooting.rst
We had lots of users reporting issues with the WinRT backend hanging forever when trying to connect to a device. This was happening because some other imported library was initializing the the main thread to STA which caused some async callback to never be called.
To work around this, we added a check to make sure the main thread is set to MTA rather than STA. Unfortunately, in cases where there is a graphical user interface library being used AND that library is properly interated with asynco so that Bleak runs in the main thread rather than in a background thread, the thread type does need to be STA for the GUI to work. So in those very specific conditions, we need to not raise an exception.
We don't know of a way to detect this automatically, so we added a new utility function …
>  backends.winrt: add allow_sta() utility function 

- CHANGELOG.rst
- bleak/backends/winrt/client.py
- bleak/backends/winrt/scanner.py
In some situations, device.details has the scan response data only and advertising data is None.
Since the ble address cannot be obtained from device.details.adv this time, the ble address is obtained from the device.details.scan (scan response data).
> backends/winrt: add address acquisition process when advertising data is None

- CHANGELOG.rst
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/p4android/scanner.py
- bleak/backends/scanner.py
- bleak/backends/winrt/scanner.py
- examples/discover.py
This is a follow-up to a818521 ("backends/scanner: always filter by service_uuids") to also filter discovered devices by the service UUIDs.
This was overlooked in that change and on Windows actually caused a regression.
Fixes: https://github.com/hbldh/bleak/issues/1576
> backends: filter discovered devices

- CHANGELOG.rst
- bleak/backends/p4android/defs.py
Use the 128bit UUID plus the Bluetooth base UUID for the notification descriptor on android devices. This fixes `Descriptor None was not found!` exceptions, as discussed in #823.
On the three android devices (API Level 33 and 32) I tested, this seems to work reliably. 
As this is just a minor fix, I did not add an entry to the `CHANGELOG.rst`. 
Let me know if that should be changed.
This fix may also address #828.
> Android: fix 'Descriptor None was not found!'

- CHANGELOG.rst
- bleak/backends/winrt/scanner.py
- bleak/backends/winrt/util.py
- docs/troubleshooting.rst
- poetry.lock
- pyproject.toml
- tests/bleak/backends/winrt/test_utils.py
In commit 4a653e6 ("backends/winrt: raise exception when trying to scan with STA") we added a check to raise an exception when trying to scan when PyWinRT set the aparatment model to STA. However, properly working GUI apps will have the apartment model set to STA but Bleak will still work because there is something pumping the Windows message loop.
We don't want to raise an exception in this case to avoid breaking working apps. We can improve the test by checking if the current thread is actually pumping the message loop by scheduling a callback via a the win32 SetTimeout function. If the callback is called, then we know that the message loop is being pumped. If not, then we probably are not going to get async callbacks from the WinRT APIs and we raise an exception in this case.
> backends/winrt: don't throw exception for properly configured GUI apps

- CHANGELOG.rst
- bleak/backends/bluezdbus/characteristic.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/characteristic.py
- bleak/backends/corebluetooth/characteristic.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/p4android/characteristic.py
- bleak/backends/p4android/client.py
- bleak/backends/winrt/characteristic.py
- bleak/backends/winrt/client.py
It has been observed that the max MTU exchange may not be complete before the connection is established, at least on Windows.
This reverts the previous attempt to work around this on Windows and instead makes the max_write_without_response_size dynamic. This way users can implement a workaround if needed but users who don't need it won't be punished with a longer connection time. The timeout in the previous workaround was also too short for some devices so it wan't complexly fixing the issue.
> backends/characteristic: make max_write_without_response_size dynamic

- AUTHORS.rst
- CHANGELOG.rst
- bleak/backends/winrt/util.py
By overriding the type definition of SetTimer, we prevent None being passed as the callback parameter. This causes problems when integrating Bleak in larger Windows applications that call SetTimer in this way.
By defining the function type definition locally, we don't override the global definition so existing code that uses None as a callback keeps working.
3. The pull request should work for Python 3.8+ on the following platforms:
- Windows 10, version 16299 (Fall Creators …
> Provide a local definition of user32.setTimer, user32.KillTimer and ole32.CoGetApartmentType on Windows

- bleak/backends/bluezdbus/manager.py
> Remove unused changed argument from BlueZManager._run_advertisement_callbacks

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
- Instead of doing a linear search of all the callbacks to find the one for the adapter, store them in a dict so the adapter path can be looked up
- Remove unused arg from _run_advertisement_callbacks
> Index BlueZ advertisement_callbacks by adapter

- .github/workflows/build_and_test.yml
- .github/workflows/build_android.yml
- .github/workflows/format_and_lint.yml
- .github/workflows/pypi-publish.yml
- CHANGELOG.rst
- poetry.lock
- pyproject.toml
Update the pin for `pyobjc-core` to add support for Python 3.13. While at it, added `3.12` and `3.13-dev` to the list of test environments.
While testing, I saw that the action runs failed on my fork due to old versions. Updated those as well.
> Add support for Python 3.13

- bleak/__init__.py
The bytes inside the example weren't properly escaped. Some IDE's threw an error, readthedocs showed this as empty.
> Escape demonstration bytes in BleakClient docstring.

- docs/troubleshooting.rst
After a lot of debugging we have discovered that disabling wifi fixes a _lot_ of sporadic "Not connected" errors we have been seeing in CI. This has been seen improving connectivity on a Raspberry Pi 4 and a Rock Pi 3C.
> Add troubleshooting step for "Not connected" problems on Raspberry Pi.

- setup.cfg
Ignore Flake E231. It disagrees with Black formatting.
> setup.cfg: ignore Flake E231

- .github/pull_request_template.md
- .github/workflows/build_and_test.yml
- CHANGELOG.rst
- CONTRIBUTING.rst
- poetry.lock
- pyproject.toml
It is out of support and some of our dependencies have stopped supporting it.
> Drop py 3.8

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
Fix a leak where service interfaces were not being removed from the service map in the BlueZ manager. This could cause a `KeyError` on later connections when calling `get_services()`.
Fixes: https://github.com/hbldh/bleak/issues/1435
> bluez: fix service interface leak

- CHANGELOG.rst
- bleak/backends/bluezdbus/client.py
Moved the try (in bluezdbus/client.py) in order to include the call to the add_device_watcher function, since it is able to throw an error when the device does not exists in bluez anymore. This causes the just opened dbus connection to not be properly closed.
fixes #1698 
3. The pull request should work for Python 3.8+ on the following platforms:
4. …
> Fix DBus connection leak

- CHANGELOG.rst
- bleak/__init__.py
Fixes: https://github.com/hbldh/bleak/issues/1743
> bleak: undeprecate response=None arg to BleakClient.write_gatt_char()

- .github/workflows/stale_issues.yml
May issues are 3rd-party or need more info. We don't aggressively close these, but there is no reason to leave them open forever.
> github: add bot to close stale issues

- docs/backends/macos.rst
Remove the can / has wording in place of can.
3. The pull request should work for Python 3.9+ on the following platforms:
- Linux distributions with BlueZ >= 5.55
- OS X / macOS >= 10.13
5. Feel free to add your name as a …
> Fix "has can" typo in macOS docs

- CHANGELOG.rst
- bleak/backends/winrt/client.py
We have found that if another app is also connected to the same BLE device, we never get the GATT session close event. This causes the `disconnect()` method to hang forever.
Instead, just close the GATT session and return immediately (and hope for the best).
Fixes: https://github.com/hbldh/bleak/issues/1759
> backends: winrt: don't wait for disconnect

- CHANGELOG.rst
- bleak/backends/winrt/client.py
- examples/philips_hue.py
This reworks pairing on WinRT backend so that hopefully we no longer need the platform-specific `protection_level` argument.
Instead, the highest possible level is tried by default.
Also fixes a few minor bugs noticed while testing.
> Winrt pair args

- .github/workflows/build_and_test.yml
- CHANGELOG.rst
- bleak/backends/bluezdbus/advertisement_monitor.py
- bleak/backends/bluezdbus/manager.py
- bleak/backends/bluezdbus/scanner.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/corebluetooth/scanner.py
- bleak/backends/winrt/client.py
- tests/bleak/backends/bluezdbus/test_deprecated_imports.py
- tests/bleak/backends/winrt/test_deprecated_imports.py
- tests/bleak/corebluetooth/test_deprecated_imports.py
There were some imports that were moved to `bleak.args.bluez` in v1.0 without a proper deprecation period. Restore these imports and add the proper deprecation warnings.
https://github.com/hbldh/bleak/issues/1783#issuecomment-3019828790
TODO: need to do the same for windows and corebluetooth
> Restore deprecated imports

- examples/service_explorer.py
Simple fix to avoid
```
__main__ INFO: [Service] 0000fff0-0000-1000-8000-00805f9b34fb (Handle: 17): Vendor specific
__main__ INFO:   [Characteristic] 0000fff1-0000-1000-8000-00805f9b34fb (Handle: 18): Vendor specific (read,notify), Error: Multiple Characteristics with this UUID, refer to your desired characteristic by the `handle` attribute instead.
```
for devices where the `UUID` is not unique.
> Fix service_explorer.py for non-unique characteristics UUID

- CHANGELOG.rst
- bleak/backends/p4android/client.py
> android / p4android: fix BleakClient connect() broken when service characteristics have descriptors

- CHANGELOG.rst
- bleak/__init__.py
- bleak/backends/bluezdbus/client.py
- bleak/backends/client.py
- bleak/backends/corebluetooth/client.py
- bleak/backends/winrt/client.py
- examples/service_explorer.py
Add a name property to the BleakClient class to retrieve the name of the connected BLE peripheral. Some OSes don't allow accessing the Device Name characteristic, so this property is useful for getting the name in a cross-platform way.
Closes: https://github.com/hbldh/bleak/issues/1802
> bleak: add BleakClient.name property

- CHANGELOG.rst
- bleak/backends/bluezdbus/manager.py
In the `BlueZManager.async_init` method, the call to `bus.connect()` was performed before the `try...except` block that handles initialization errors.
If `bus.connect()` itself were to fail, the exception would not be caught by the block, and the `bus.disconnect()` cleanup logic would not run.
This commit moves the `await bus.connect()` call inside the `try` block to ensure that any connection-related exceptions are properly handled and the bus is disconnected.
> bluezdbus: improve D-Bus connection error handling in manager
